### ISSUE TITLE
Public Facing User Profile pages

### ISSUE THREAD

**Issue by astonshane** [astonshane/EventsNearMe#59]
* [x] create public profile View
* [x] show user's name / profile picture
* [x] show user's contact details
* [x] show user's interests
* [x] show events that that user is attending
* [x] show a link to the private profile page if a User is viewing their own Profile
* [x] show a link to the public profile page if a User is viewing their private Profile
* [x] user links from around the site link to this page

**Comment by astonshane** [comment]
@chao-e are you coming along with this?

**Comment by chao-e** [comment]
currently working on it
